services:
  java: 
    image: "gradle:7.2-jdk17"
    container_name: Gradle
    volumes: 
      - ./:/home/gradle
    command: tail -F afilethatdoesnotexist
    stdin_open: true
    tty: true
  selenium:
    image: "selenium/standalone-firefox:latest"
    container_name: Selenium
    
