/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seo.tool;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(1, "app should have a greeting");
    }
}
